server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri:  mongodb://47.102.124.148:27017
      database: xc_media
#rabbitmq配置
  rabbitmq:
    host: 47.106.218.133
    port: 5672
    username: admin
    password: ois@pass
    virtualHost: /
xc-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: F:/develop/video/
  ffmpeg-path: D:/Program Files/ffmpeg-20180227-fa0c9d6-win64-static/bin/ffmpeg.exe